export function getCountryFlag(countryCode?: string | null): string {
  if (!countryCode || countryCode.length !== 2) return "🌍";
  const code = countryCode.toUpperCase();
  const offset = 127397;
  try {
    return String.fromCodePoint(...[...code].map((c) => c.charCodeAt(0) + offset));
  } catch {
    return "🌍";
  }
}

export function getCountryFlagByName(name?: string | null): string {
  if (!name) return "🌍";
  const map: Record<string, string> = {
    russia: "🇷🇺",
    "russian federation": "🇷🇺",
    ukraine: "🇺🇦",
    kazakhstan: "🇰🇿",
    china: "🇨🇳",
    philippines: "🇵🇭",
    myanmar: "🇲🇲",
    indonesia: "🇮🇩",
    usa: "🇺🇸",
    "united states": "🇺🇸",
    uk: "🇬🇧",
    "united kingdom": "🇬🇧",
    germany: "🇩🇪",
    france: "🇫🇷",
    italy: "🇮🇹",
    spain: "🇪🇸",
    poland: "🇵🇱",
    netherlands: "🇳🇱",
    brazil: "🇧🇷",
    india: "🇮🇳",
    pakistan: "🇵🇰",
    bangladesh: "🇧🇩",
    turkey: "🇹🇷",
    vietnam: "🇻🇳",
    thailand: "🇹🇭",
    malaysia: "🇲🇾",
    egypt: "🇪🇬",
    nigeria: "🇳🇬",
    kenya: "🇰🇪",
    "south africa": "🇿🇦",
    mexico: "🇲🇽",
    argentina: "🇦🇷",
    colombia: "🇨🇴",
    peru: "🇵🇪",
    chile: "🇨🇱",
    canada: "🇨🇦",
    australia: "🇦🇺",
    japan: "🇯🇵",
    "south korea": "🇰🇷",
    taiwan: "🇹🇼",
    "hong kong": "🇭🇰",
    singapore: "🇸🇬",
    romania: "🇷🇴",
    czech: "🇨🇿",
    hungary: "🇭🇺",
    portugal: "🇵🇹",
    greece: "🇬🇷",
    sweden: "🇸🇪",
    norway: "🇳🇴",
    denmark: "🇩🇰",
    finland: "🇫🇮",
    belgium: "🇧🇪",
    austria: "🇦🇹",
    switzerland: "🇨🇭",
    israel: "🇮🇱",
    uae: "🇦🇪",
    saudi: "🇸🇦",
    iran: "🇮🇷",
    uzbekistan: "🇺🇿",
    belarus: "🇧🇾",
    moldova: "🇲🇩",
    azerbaijan: "🇦🇿",
    armenia: "🇦🇲",
    georgia: "🇬🇪",
    kyrgyzstan: "🇰🇬",
    tajikistan: "🇹🇯",
    turkmenistan: "🇹🇲",
    latvia: "🇱🇻",
    lithuania: "🇱🇹",
    estonia: "🇪🇪",
    serbia: "🇷🇸",
    bulgaria: "🇧🇬",
    croatia: "🇭🇷",
    slovenia: "🇸🇮",
    slovakia: "🇸🇰",
    bosnia: "🇧🇦",
    macedonia: "🇲🇰",
    albania: "🇦🇱",
    montenegro: "🇲🇪",
    cyprus: "🇨🇾",
    malta: "🇲🇹",
    iceland: "🇮🇸",
    ireland: "🇮🇪",
    luxembourg: "🇱🇺",
    monaco: "🇲🇨",
    liechtenstein: "🇱🇮",
    andorra: "🇦🇩",
    "san marino": "🇸🇲",
    vatican: "🇻🇦",
  };
  return map[name.toLowerCase().trim()] || "🌍";
}
